spring:
  application:
    name: credit-appraiser-service
  # BROKER CONNECTION
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://tech-bank:GYqQlHPH8QP6InO@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# QUEUE
mq:
  queues:
    credit-card-emit: credit-card-emit
