spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: tech-bank
      password: GYqQlHPH8QP6InO

### Create an env variable to name and password

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
